### ISSUE TITLE
提示连接huggingface失败

### ISSUE THREAD

**Issue by Acquire2** [taishan1994/W2NER_predict#15]
环境配置完成后，将conll03数据集放入data下，其余没有改动，直接在自己电脑上运行，提示如下

2023-12-28 15:52:56 - INFO: Loading Data
Traceback (most recent call last):
  File "D:\software\Anaconda3\W2NER_predict-main\main.py", line 201, in <module>
    datasets = data_loader.load_data_bert(config)
  File "D:\software\Anaconda3\W2NER_predict-main\data_loader.py", line 233, in load_data_bert
    tokenizer = AutoTokenizer.from_pretrained(config.bert_name, cache_dir="./cache/")
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 473, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 334, in get_tokenizer_config
    resolved_config_file = cached_path(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\file_utils.py", line 1625, in cached_path
    output_path = get_from_cache(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\file_utils.py", line 1849, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by Acquire2** [comment]
后百度，选择科学上网全局模式，依旧提示连接huggingface失败，提示如下

2023-12-28 15:56:30 - INFO: Loading Data
Traceback (most recent call last):
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\software\Anaconda3\envs\W2NER\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\software\Anaconda3\envs\W2NER\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\software\Anaconda3\envs\W2NER\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-large-cased/tree/main?recursive=True&expand=False (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\Anaconda3\W2NER_predict-main\main.py", line 201, in <module>
    datasets = data_loader.load_data_bert(config)
  File "D:\software\Anaconda3\W2NER_predict-main\data_loader.py", line 233, in load_data_bert
    tokenizer = AutoTokenizer.from_pretrained(config.bert_name, cache_dir="./cache/")
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 480, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\models\auto\configuration_auto.py", line 580, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\configuration_utils.py", line 550, in get_config_dict
    configuration_file = get_configuration_file(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\configuration_utils.py", line 841, in get_configuration_file
    all_files = get_list_of_files(
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\transformers\file_utils.py", line 1952, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\huggingface_hub\hf_api.py", line 2605, in list_repo_files
    return [
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\huggingface_hub\hf_api.py", line 2605, in <listcomp>
    return [
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\huggingface_hub\hf_api.py", line 2741, in list_repo_tree
    for path_info in paginate(path=tree_url, headers=headers, params={"recursive": recursive, "expand": expand}):
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\huggingface_hub\utils\_pagination.py", line 35, in paginate
    r = session.get(path, params=params, headers=headers)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "D:\software\Anaconda3\envs\W2NER\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-large-cased/tree/main?recursive=True&expand=False (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))"), '(Request ID: 82a718bd-cc52-42be-97dc-1274e9a7bc6e)')

**Comment by taishan1994** [comment]
可以去hugging face上面把权重下载下来，然后再加载本地的。

**Comment by Acquire2** [comment]
嗯嗯 感谢大佬 下载好也跑起来了
